<?php $isEditing=is_array($editingProduct);$p=$editingProduct??[];$action=$isEditing?url('admin-product-update',['id'=>$p['id_producto']]):url('admin-product-save');?>
<div class="admin-page-actions"><div><span class="admin-kicker">Productos</span><h2><?=$isEditing?'Editar producto':'Nuevo producto'?></h2><p>Los cambios se guardan en PostgreSQL.</p></div><a class="admin-secondary-button" href="<?=e(url('admin-products'))?>">Cancelar</a></div>
<form class="admin-form-layout" method="post" enctype="multipart/form-data" action="<?=e($action)?>"><?=csrf_input()?><input type="hidden" name="MAX_FILE_SIZE" value="2097152"><section class="admin-panel admin-form-main"><h3>Información general</h3><div class="admin-form-grid">
<label class="admin-field admin-field--wide"><span>Nombre *</span><input name="nombre" class="form-control" maxlength="160" required value="<?=e($p['nombre']??'')?>"></label>
<label class="admin-field"><span>Código de barras</span><input name="codigo_barra" class="form-control" maxlength="80" value="<?=e($p['codigo_barra']??'')?>"></label>
<label class="admin-field"><span>Categoría *</span><select name="id_categoria" class="form-select" required><option value="">Seleccionar</option><?php foreach($adminCategories as $c):?><option value="<?=e($c['id_categoria'])?>" <?=($p['id_categoria']??null)==$c['id_categoria']?'selected':''?>><?=e($c['nombre'])?></option><?php endforeach;?></select></label>
<label class="admin-field admin-field--wide"><span>Descripción</span><textarea name="descripcion" maxlength="2000" class="form-control" rows="4"><?=e($p['descripcion']??'')?></textarea></label>
<label class="admin-field"><span>Marca</span><input name="marca" maxlength="100" class="form-control" value="<?=e($p['marca']??'')?>"></label><label class="admin-field"><span>Presentación</span><input name="presentacion" maxlength="100" class="form-control" value="<?=e($p['presentacion']??'')?>"></label>
<label class="admin-field"><span>Unidad</span><select name="unidad_medida" class="form-select"><?php foreach(['Unidad','L','ML','KG','G'] as $u):?><option <?=($p['unidad_medida']??'Unidad')===$u?'selected':''?>><?=e($u)?></option><?php endforeach;?></select></label>
<label class="admin-field"><span>Precio *</span><input name="precio" class="form-control" type="number" step="0.01" min="0" required value="<?=e($p['precio']??'')?>"></label><label class="admin-field"><span>Stock *</span><input name="stock" class="form-control" type="number" min="0" required value="<?=e($p['stock']??0)?>"></label><label class="admin-check"><input name="activo" type="checkbox" <?=!isset($p['activo'])||in_array($p['activo'],[true,1,'t'],true)?'checked':''?>> Producto activo</label></div></section>
<aside class="admin-panel admin-image-panel"><h3>Imagen</h3><div class="admin-image-preview" data-image-preview><?php if(!empty($p['imagen'])):?><img src="<?=e(product_image($p['imagen']))?>" alt="Imagen actual"><?php else:?><span>Vista previa</span><?php endif;?></div><label class="admin-upload">Seleccionar imagen<input name="imagen" type="file" accept=".jpg,.jpeg,.png,.webp,image/png,image/jpeg,image/webp" data-image-input data-max-size="2097152"></label><small>JPG, JPEG, PNG o WebP; máximo 2 MB. Al editar, dejá el campo vacío para conservar la imagen actual.</small><p class="category-image-error" data-product-image-error role="alert" aria-live="polite"></p><button class="admin-primary-button" type="submit"><?=$isEditing?'Guardar cambios':'Guardar producto'?></button></aside></form>
