<?php
declare(strict_types=1);
final class CheckoutController
{
 public function __construct(private readonly CheckoutRepository $repo,private readonly Cart $cart,private readonly string $storagePath,private readonly array $paymentConfig){}
 public function show():void{if(!is_customer_authenticated()){flash('info','Iniciá sesión o creá una cuenta para continuar.');header('Location: '.url('login'),true,303);exit;}if(!$this->cart->rawItems()){flash('warning','Tu carrito está vacío.');header('Location: '.url('cart'),true,303);exit;}render('orders/checkout.php',['pageTitle'=>'Finalizar compra','customer'=>customer_user(),'transfer'=>$this->paymentConfig]);}
 public function confirm():never{if(!is_customer_authenticated()){header('Location: '.url('login'),true,303);exit;}if(!verify_csrf($_POST['csrf_token']??null)){http_response_code(403);exit('Solicitud inválida.');}$method=(string)($_POST['metodo']??'');$address=trim((string)($_POST['direccion']??''));if(!in_array($method,['EFECTIVO','TRANSFERENCIA'],true)||mb_strlen($address)<8||mb_strlen($address)>500){flash('danger','Indicá una dirección y una forma de pago válidas.');header('Location: '.url('checkout'),true,303);exit;}$proof=null;try{if($method==='TRANSFERENCIA')$proof=$this->storeProof();$id=$this->repo->createOrder((int)customer_user()['id'],$this->cart->rawItems(),$method,$address,$proof);$_SESSION['cart']=[];header('Location: '.url('order-confirmation',['id'=>$id]),true,303);exit;}catch(Throwable $e){if($proof&&is_file($this->storagePath.'/'.$proof))unlink($this->storagePath.'/'.$proof);error_log('Checkout: '.$e->getMessage());flash('danger',$e instanceof InvalidArgumentException||$e instanceof RuntimeException?$e->getMessage():'No pudimos confirmar el pedido.');header('Location: '.url('checkout'),true,303);exit;}}
 public function confirmation():void{if(!is_customer_authenticated()){header('Location: '.url('login'),true,303);exit;}$id=filter_var($_GET['id']??null,FILTER_VALIDATE_INT);$order=$id?$this->repo->order((int)$id,(int)customer_user()['id']):null;if(!$order){http_response_code(404);render('errors/404.php');return;}render('orders/confirmation.php',['pageTitle'=>'Pedido confirmado','order'=>$order]);}
 private function storeProof():string{$f=$_FILES['comprobante']??null;if(!is_array($f)||($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new InvalidArgumentException('Adjuntá el comprobante de transferencia.');if(($f['size']??0)>5*1024*1024)throw new InvalidArgumentException('El comprobante no puede superar 5 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'][$mime]??null;if(!$ext)throw new InvalidArgumentException('El comprobante debe ser JPG, PNG, WebP o PDF.');if(!is_dir($this->storagePath)&&!mkdir($this->storagePath,0700,true))throw new RuntimeException('No se pudo preparar el almacenamiento.');$name=bin2hex(random_bytes(24)).'.'.$ext;if(!move_uploaded_file($f['tmp_name'],$this->storagePath.'/'.$name))throw new RuntimeException('No se pudo guardar el comprobante.');return $name;}
}
